# coding: utf-8

"""
    Qiara Home Security API

    API for the Qiara home security system, extracted from decompiled Android APK. This API manages authentication, home nodes, video streaming, recording, pairing, and history. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.read_endpoints_request import ReadEndpointsRequest

class TestReadEndpointsRequest(unittest.TestCase):
    """ReadEndpointsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReadEndpointsRequest:
        """Test ReadEndpointsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReadEndpointsRequest`
        """
        model = ReadEndpointsRequest()
        if include_optional:
            return ReadEndpointsRequest(
                list = [
                    openapi_client.models.api_endpoint_read_body_list_inner.ApiEndpointReadBody_list_inner(
                        node_id = 1001, 
                        eps = [
                            'temperature'
                            ], )
                    ]
            )
        else:
            return ReadEndpointsRequest(
                list = [
                    openapi_client.models.api_endpoint_read_body_list_inner.ApiEndpointReadBody_list_inner(
                        node_id = 1001, 
                        eps = [
                            'temperature'
                            ], )
                    ],
        )
        """

    def testReadEndpointsRequest(self):
        """Test ReadEndpointsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
