# coding: utf-8

"""
    Qiara Home Security API

    API for the Qiara home security system, extracted from decompiled Android APK. This API manages authentication, home nodes, video streaming, recording, pairing, and history. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_challenge import ApiChallenge

class TestApiChallenge(unittest.TestCase):
    """ApiChallenge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiChallenge:
        """Test ApiChallenge
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiChallenge`
        """
        model = ApiChallenge()
        if include_optional:
            return ApiChallenge(
                challenge = 'a1b2c3d4e5f6'
            )
        else:
            return ApiChallenge(
                challenge = 'a1b2c3d4e5f6',
        )
        """

    def testApiChallenge(self):
        """Test ApiChallenge"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
