# coding: utf-8

"""
    Qiara Home Security API

    API for the Qiara home security system, extracted from decompiled Android APK. This API manages authentication, home nodes, video streaming, recording, pairing, and history. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_endpoint_write_body_list_inner import ApiEndpointWriteBodyListInner

class TestApiEndpointWriteBodyListInner(unittest.TestCase):
    """ApiEndpointWriteBodyListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiEndpointWriteBodyListInner:
        """Test ApiEndpointWriteBodyListInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiEndpointWriteBodyListInner`
        """
        model = ApiEndpointWriteBodyListInner()
        if include_optional:
            return ApiEndpointWriteBodyListInner(
                node_id = 1001,
                eps = [
                    None
                    ]
            )
        else:
            return ApiEndpointWriteBodyListInner(
                node_id = 1001,
                eps = [
                    None
                    ],
        )
        """

    def testApiEndpointWriteBodyListInner(self):
        """Test ApiEndpointWriteBodyListInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
