# coding: utf-8

"""
    Qiara Home Security API

    API for the Qiara home security system, extracted from decompiled Android APK. This API manages authentication, home nodes, video streaming, recording, pairing, and history. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_control_video_recorder(self) -> None:
        """Test case for control_video_recorder

        Control video recorder
        """
        pass

    def test_create_session(self) -> None:
        """Test case for create_session

        Create new session
        """
        pass

    def test_delete_history(self) -> None:
        """Test case for delete_history

        Delete history items
        """
        pass

    def test_delete_nodes(self) -> None:
        """Test case for delete_nodes

        Delete nodes
        """
        pass

    def test_delete_video_recordings(self) -> None:
        """Test case for delete_video_recordings

        Delete video recordings
        """
        pass

    def test_get_challenge(self) -> None:
        """Test case for get_challenge

        Get authentication challenge
        """
        pass

    def test_get_history(self) -> None:
        """Test case for get_history

        Get event history
        """
        pass

    def test_get_nodes(self) -> None:
        """Test case for get_nodes

        Get home nodes
        """
        pass

    def test_get_revision_update(self) -> None:
        """Test case for get_revision_update

        Get revision update
        """
        pass

    def test_get_stream_snapshot(self) -> None:
        """Test case for get_stream_snapshot

        Get live stream snapshot
        """
        pass

    def test_get_video_recordings(self) -> None:
        """Test case for get_video_recordings

        Get video recordings
        """
        pass

    def test_manage_home_pairing(self) -> None:
        """Test case for manage_home_pairing

        Manage device pairing
        """
        pass

    def test_open_video_stream(self) -> None:
        """Test case for open_video_stream

        Open video stream
        """
        pass

    def test_read_endpoints(self) -> None:
        """Test case for read_endpoints

        Read endpoint values
        """
        pass

    def test_update_firmware(self) -> None:
        """Test case for update_firmware

        Update firmware
        """
        pass

    def test_update_revision(self) -> None:
        """Test case for update_revision

        Update revision
        """
        pass

    def test_write_endpoints(self) -> None:
        """Test case for write_endpoints

        Write endpoint values
        """
        pass


if __name__ == '__main__':
    unittest.main()
