# coding: utf-8

"""
    Qiara Home Security API

    API for the Qiara home security system, extracted from decompiled Android APK. This API manages authentication, home nodes, video streaming, recording, pairing, and history. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_nodes_response import ApiNodesResponse

class TestApiNodesResponse(unittest.TestCase):
    """ApiNodesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiNodesResponse:
        """Test ApiNodesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiNodesResponse`
        """
        model = ApiNodesResponse()
        if include_optional:
            return ApiNodesResponse(
                hash_i = 1234567890,
                list = [
                    openapi_client.models.node.Node(
                        discarded = 0, 
                        hash_t = 9876543210, 
                        id = 1001, 
                        type_name = 'camera', )
                    ]
            )
        else:
            return ApiNodesResponse(
                hash_i = 1234567890,
                list = [
                    openapi_client.models.node.Node(
                        discarded = 0, 
                        hash_t = 9876543210, 
                        id = 1001, 
                        type_name = 'camera', )
                    ],
        )
        """

    def testApiNodesResponse(self):
        """Test ApiNodesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
