# coding: utf-8

"""
    Qiara Home Security API

    API for the Qiara home security system, extracted from decompiled Android APK. This API manages authentication, home nodes, video streaming, recording, pairing, and history. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_new_session_body import ApiNewSessionBody

class TestApiNewSessionBody(unittest.TestCase):
    """ApiNewSessionBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiNewSessionBody:
        """Test ApiNewSessionBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiNewSessionBody`
        """
        model = ApiNewSessionBody()
        if include_optional:
            return ApiNewSessionBody(
                cust_id = 12345,
                challenge_rsp = '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08'
            )
        else:
            return ApiNewSessionBody(
                cust_id = 12345,
                challenge_rsp = '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
        )
        """

    def testApiNewSessionBody(self):
        """Test ApiNewSessionBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
