# coding: utf-8

"""
    Qiara Home Security API

    API for the Qiara home security system, extracted from decompiled Android APK. This API manages authentication, home nodes, video streaming, recording, pairing, and history. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_history_response import ApiHistoryResponse

class TestApiHistoryResponse(unittest.TestCase):
    """ApiHistoryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiHistoryResponse:
        """Test ApiHistoryResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiHistoryResponse`
        """
        model = ApiHistoryResponse()
        if include_optional:
            return ApiHistoryResponse(
                list = [
                    openapi_client.models.history_item.HistoryItem(
                        id = 500123, 
                        node_id = 1001, 
                        timestamp = 1638360123, 
                        value = 'motion_detected', 
                        is_trigger = False, 
                        trigger_source = 1002, 
                        opening_type = 'door', 
                        room = 'Living Room', 
                        area = 'zone_1', 
                        user_name = 'john_doe', 
                        kpd_code_label = 'main_code', )
                    ]
            )
        else:
            return ApiHistoryResponse(
                list = [
                    openapi_client.models.history_item.HistoryItem(
                        id = 500123, 
                        node_id = 1001, 
                        timestamp = 1638360123, 
                        value = 'motion_detected', 
                        is_trigger = False, 
                        trigger_source = 1002, 
                        opening_type = 'door', 
                        room = 'Living Room', 
                        area = 'zone_1', 
                        user_name = 'john_doe', 
                        kpd_code_label = 'main_code', )
                    ],
        )
        """

    def testApiHistoryResponse(self):
        """Test ApiHistoryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
