# coding: utf-8

"""
    Qiara Home Security API

    API for the Qiara home security system, extracted from decompiled Android APK. This API manages authentication, home nodes, video streaming, recording, pairing, and history. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class ApiPairingStart(BaseModel):
    """
    ApiPairingStart
    """ # noqa: E501
    node_type: StrictStr = Field(description="Type of node to pair. Maps to device types in the Qiara home security system. - HOMELABCAM: Camera (MainCamera or SlaveCamera) - HOMELABSRN: Siren - HOMELABDWS: Door/Window Sensor - HOMELABPIR: PIR Motion Sensor   - HOMELABKPD: Keypad ")
    op: StrictStr = Field(description="Operation type for pairing process. - start_adapter: Start adapter and begin pairing - stop: Stop pairing process - poll: Poll for pairing status - next: Move to next step in pairing ")
    adapter_type: StrictStr = Field(description="Adapter type for the pairing process. Default is Adapter.DomusAdapter which is used for the Qiara/Domus home security system devices. ")
    __properties: ClassVar[List[str]] = ["node_type", "op", "adapter_type"]

    @field_validator('node_type')
    def node_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['HOMELABCAM', 'HOMELABSRN', 'HOMELABDWS', 'HOMELABPIR', 'HOMELABKPD']):
            raise ValueError("must be one of enum values ('HOMELABCAM', 'HOMELABSRN', 'HOMELABDWS', 'HOMELABPIR', 'HOMELABKPD')")
        return value

    @field_validator('op')
    def op_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['start_adapter', 'stop', 'poll', 'next']):
            raise ValueError("must be one of enum values ('start_adapter', 'stop', 'poll', 'next')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiPairingStart from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiPairingStart from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "node_type": obj.get("node_type"),
            "op": obj.get("op") if obj.get("op") is not None else 'start_adapter',
            "adapter_type": obj.get("adapter_type") if obj.get("adapter_type") is not None else 'Adapter.DomusAdapter'
        })
        return _obj


