# coding: utf-8

"""
    Qiara Home Security API

    API for the Qiara home security system, extracted from decompiled Android APK. This API manages authentication, home nodes, video streaming, recording, pairing, and history. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class HistoryItem(BaseModel):
    """
    HistoryItem
    """ # noqa: E501
    id: StrictInt = Field(description="Unique history event ID")
    node_id: StrictInt = Field(description="ID of the node that triggered the event")
    timestamp: Optional[StrictInt] = Field(default=None, description="Unix timestamp of the event")
    value: StrictStr = Field(description="Event type/value (e.g., \"door_open\", \"motion_detected\")")
    is_trigger: Optional[StrictBool] = Field(default=None, description="Whether this event triggered another action")
    trigger_source: Optional[StrictInt] = Field(default=None, description="Node ID that triggered this event (if applicable)")
    opening_type: Optional[StrictStr] = Field(default=None, description="Type of opening (for door/window sensors)")
    room: Optional[StrictStr] = Field(default=None, description="Custom room name")
    area: Optional[StrictStr] = Field(default=None, description="Area key/identifier")
    user_name: Optional[StrictStr] = Field(default=None, description="Username associated with the event")
    kpd_code_label: Optional[StrictStr] = Field(default=None, description="Keypad code label (for keypad events)")
    __properties: ClassVar[List[str]] = ["id", "node_id", "timestamp", "value", "is_trigger", "trigger_source", "opening_type", "room", "area", "user_name", "kpd_code_label"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HistoryItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if timestamp (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp is None and "timestamp" in self.model_fields_set:
            _dict['timestamp'] = None

        # set to None if is_trigger (nullable) is None
        # and model_fields_set contains the field
        if self.is_trigger is None and "is_trigger" in self.model_fields_set:
            _dict['is_trigger'] = None

        # set to None if trigger_source (nullable) is None
        # and model_fields_set contains the field
        if self.trigger_source is None and "trigger_source" in self.model_fields_set:
            _dict['trigger_source'] = None

        # set to None if opening_type (nullable) is None
        # and model_fields_set contains the field
        if self.opening_type is None and "opening_type" in self.model_fields_set:
            _dict['opening_type'] = None

        # set to None if room (nullable) is None
        # and model_fields_set contains the field
        if self.room is None and "room" in self.model_fields_set:
            _dict['room'] = None

        # set to None if area (nullable) is None
        # and model_fields_set contains the field
        if self.area is None and "area" in self.model_fields_set:
            _dict['area'] = None

        # set to None if user_name (nullable) is None
        # and model_fields_set contains the field
        if self.user_name is None and "user_name" in self.model_fields_set:
            _dict['user_name'] = None

        # set to None if kpd_code_label (nullable) is None
        # and model_fields_set contains the field
        if self.kpd_code_label is None and "kpd_code_label" in self.model_fields_set:
            _dict['kpd_code_label'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HistoryItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "node_id": obj.get("node_id"),
            "timestamp": obj.get("timestamp"),
            "value": obj.get("value"),
            "is_trigger": obj.get("is_trigger"),
            "trigger_source": obj.get("trigger_source"),
            "opening_type": obj.get("opening_type"),
            "room": obj.get("room"),
            "area": obj.get("area"),
            "user_name": obj.get("user_name"),
            "kpd_code_label": obj.get("kpd_code_label")
        })
        return _obj


